name: Playwright Tests
on:
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
        working-directory: ./KMS-Lighthouse
      - name: Install Playwright Browsers
        run: npx playwright install
        working-directory: ./KMS-Lighthouse
      - name: Run Playwright tests
        run: npx playwright test
        working-directory: ./KMS-Lighthouse
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: KMS-Lighthouse/playwright-report/
          retention-days: 30
